# Generated by Django 4.0.4 on 2022-06-01 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('IdB', models.IntegerField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=128)),
                ('Categorie', models.CharField(max_length=30)),
                ('Auteur', models.CharField(max_length=30)),
                ('Classement', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('MotDePasse', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='book_fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.user')),
            ],
        ),
    ]
