# Generated by Django 4.0.4 on 2022-06-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_fav',
            name='Nom',
        ),
        migrations.RemoveField(
            model_name='book_fav',
            name='User',
        ),
        migrations.AddField(
            model_name='book_fav',
            name='NomLivre',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_fav',
            name='Username',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
