# Generated by Django 4.0.4 on 2022-05-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifiant', models.CharField(max_length=30)),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('MotDePasse', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
