# Generated by Django 4.0.4 on 2022-06-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
