# Generated by Django 4.0.4 on 2022-05-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_user_delete_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
