# Generated by Django 4.0.4 on 2022-06-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('NumeroDeTelephone', models.CharField(max_length=14)),
                ('Message', models.CharField(max_length=400)),
            ],
        ),
    ]
