# Generated by Django 4.0.4 on 2022-05-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Utilisateur',
        ),
    ]
